//! Build script that discovers .gtest files and generates Rust test functions.
//!
//! Each test case in a .gtest file becomes a `#[test]` function in the
//! generated output, enabling `cargo test`, IDE integration, and filtering.

use std::collections::HashMap;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let spec_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("tests")
        .join("spec");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = PathBuf::from(&out_dir).join("spec_tests.rs");

    println!("cargo:rerun-if-changed={}", spec_dir.display());

    let mut output = String::new();
    let mut test_count = 0;

    // Walk the spec directory for .gtest files
    if spec_dir.exists() {
        for entry in walk_dir(&spec_dir) {
            if entry.extension().is_some_and(|e| e == "gtest") {
                println!("cargo:rerun-if-changed={}", entry.display());
                match parse_gtest_file(&entry) {
                    Ok(file) => {
                        let rel = entry
                            .strip_prefix(&spec_dir)
                            .unwrap()
                            .to_string_lossy()
                            .replace('\\', "/");
                        let module_name = sanitize_module_name(&rel);
                        test_count += generate_tests(&mut output, &file, &module_name, &rel);
                    }
                    Err(e) => {
                        panic!("Failed to parse {}: {}", entry.display(), e);
                    }
                }
            }
        }
    }

    // Write a summary comment
    let header = format!(
        "// Auto-generated by build.rs from tests/spec/**/*.gtest\n\
         // Total: {} test(s)\n\
         // DO NOT EDIT\n\n",
        test_count
    );

    fs::write(&out_path, header + &output).unwrap();
}

// ---------------------------------------------------------------------------
// .gtest parser
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct GtestFile {
    meta: Meta,
    tests: Vec<TestCase>,
}

#[derive(Debug, Default)]
struct Meta {
    language: String,
    model: String,
    section: String,
    title: String,
    dataset: String,
    requires: Vec<String>,
    tags: Vec<String>,
}

#[derive(Debug)]
struct TestCase {
    name: String,
    query: Option<String>,
    statements: Vec<String>,
    setup: Vec<String>,
    params: HashMap<String, String>,
    tags: Vec<String>,
    requires: Vec<String>,
    language: Option<String>,
    dataset: Option<String>,
    skip: Option<String>,
    expect: Expect,
    variants: HashMap<String, String>,
}

#[derive(Debug, Default)]
struct Expect {
    rows: Vec<Vec<String>>,
    ordered: bool,
    count: Option<usize>,
    empty: bool,
    error: Option<String>,
    hash: Option<String>,
    precision: Option<u32>,
    columns: Vec<String>,
}

fn parse_gtest_file(path: &Path) -> Result<GtestFile, String> {
    let content = fs::read_to_string(path).map_err(|e| format!("read error: {e}"))?;

    let lines: Vec<&str> = content.lines().collect();
    let mut idx = 0;

    // Skip leading comments and blank lines
    while idx < lines.len() {
        let trimmed = lines[idx].trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            idx += 1;
        } else {
            break;
        }
    }

    // Parse meta block
    let meta = parse_meta(&lines, &mut idx)?;

    // Parse tests list
    let tests = parse_tests(&lines, &mut idx)?;

    Ok(GtestFile { meta, tests })
}

fn parse_meta(lines: &[&str], idx: &mut usize) -> Result<Meta, String> {
    let mut meta = Meta::default();

    // Expect "meta:"
    skip_blank_and_comments(lines, idx);
    if *idx >= lines.len() || lines[*idx].trim() != "meta:" {
        return Err(format!(
            "Expected 'meta:' at line {}, found: '{}'",
            *idx + 1,
            lines.get(*idx).unwrap_or(&"<EOF>")
        ));
    }
    *idx += 1;

    // Parse meta fields (indented key: value pairs)
    while *idx < lines.len() {
        let line = lines[*idx];
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            *idx += 1;
            continue;
        }
        // If not indented, we've left the meta block
        if !line.starts_with(' ') && !line.starts_with('\t') {
            break;
        }
        if let Some((key, value)) = parse_kv(trimmed) {
            match key {
                "language" => meta.language = value.to_string(),
                "model" => meta.model = value.to_string(),
                "section" => meta.section = unquote(value),
                "title" => meta.title = value.to_string(),
                "dataset" => meta.dataset = value.to_string(),
                "requires" => meta.requires = parse_yaml_list(value),
                "tags" => meta.tags = parse_yaml_list(value),
                _ => {} // ignore unknown keys
            }
        }
        *idx += 1;
    }

    // Default language
    if meta.language.is_empty() {
        meta.language = "gql".to_string();
    }
    if meta.dataset.is_empty() {
        meta.dataset = "empty".to_string();
    }

    Ok(meta)
}

fn parse_tests(lines: &[&str], idx: &mut usize) -> Result<Vec<TestCase>, String> {
    let mut tests = Vec::new();

    skip_blank_and_comments(lines, idx);

    // Expect "tests:"
    if *idx >= lines.len() || lines[*idx].trim() != "tests:" {
        return Err(format!(
            "Expected 'tests:' at line {}, found: '{}'",
            *idx + 1,
            lines.get(*idx).unwrap_or(&"<EOF>")
        ));
    }
    *idx += 1;

    // Parse list of test cases
    while *idx < lines.len() {
        skip_blank_and_comments(lines, idx);
        if *idx >= lines.len() {
            break;
        }

        let trimmed = lines[*idx].trim();

        // Each test starts with "- name: <test_name>"
        if trimmed.starts_with("- name:") {
            let test = parse_single_test(lines, idx)?;
            tests.push(test);
        } else {
            break;
        }
    }

    Ok(tests)
}

fn parse_single_test(lines: &[&str], idx: &mut usize) -> Result<TestCase, String> {
    let mut tc = TestCase {
        name: String::new(),
        query: None,
        statements: Vec::new(),
        setup: Vec::new(),
        params: HashMap::new(),
        tags: Vec::new(),
        requires: Vec::new(),
        language: None,
        dataset: None,
        skip: None,
        expect: Expect::default(),
        variants: HashMap::new(),
    };

    // First line: "- name: xxx"
    let first = lines[*idx].trim();
    if let Some((_, name)) = parse_kv(&first[2..]) {
        // strip leading "- "
        tc.name = unquote(name.trim());
    }
    *idx += 1;

    // Parse remaining fields until next "- name:" or end
    while *idx < lines.len() {
        let line = lines[*idx];
        let trimmed = line.trim();

        // Skip comments
        if trimmed.starts_with('#') {
            *idx += 1;
            continue;
        }

        // End of this test: next test item or end of list
        if trimmed.starts_with("- name:") {
            break;
        }

        // Blank lines are OK
        if trimmed.is_empty() {
            *idx += 1;
            continue;
        }

        if let Some((key, value)) = parse_kv(trimmed) {
            match key {
                "query" => {
                    if value == "|" {
                        tc.query = Some(parse_block_scalar(lines, idx));
                    } else {
                        tc.query = Some(unquote(value));
                        *idx += 1;
                    }
                }
                "skip" => {
                    tc.skip = Some(unquote(value));
                    *idx += 1;
                }
                "setup" => {
                    *idx += 1;
                    tc.setup = parse_string_list(lines, idx);
                }
                "statements" => {
                    *idx += 1;
                    tc.statements = parse_string_list(lines, idx);
                }
                "tags" => {
                    tc.tags = parse_yaml_list(value);
                    *idx += 1;
                }
                "requires" => {
                    tc.requires = parse_yaml_list(value);
                    *idx += 1;
                }
                "language" => {
                    tc.language = Some(unquote(value));
                    *idx += 1;
                }
                "dataset" => {
                    tc.dataset = Some(unquote(value));
                    *idx += 1;
                }
                "params" => {
                    *idx += 1;
                    tc.params = parse_params(lines, idx);
                }
                "expect" => {
                    *idx += 1;
                    tc.expect = parse_expect(lines, idx)?;
                }
                "variants" => {
                    *idx += 1;
                    tc.variants = parse_variants(lines, idx);
                }
                _ => {
                    *idx += 1;
                }
            }
        } else {
            *idx += 1;
        }
    }

    Ok(tc)
}

fn parse_expect(lines: &[&str], idx: &mut usize) -> Result<Expect, String> {
    let mut expect = Expect::default();

    while *idx < lines.len() {
        let trimmed = lines[*idx].trim();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            *idx += 1;
            continue;
        }

        // End if we hit a non-indented line or next test
        if trimmed.starts_with("- name:") {
            break;
        }

        // Check if we're at a peer-level key (not indented enough for expect)
        if !lines[*idx].starts_with(' ') && !lines[*idx].starts_with('\t') {
            break;
        }

        if let Some((key, value)) = parse_kv(trimmed) {
            match key {
                "ordered" => {
                    expect.ordered = value == "true";
                    *idx += 1;
                }
                "count" => {
                    expect.count = value.parse().ok();
                    *idx += 1;
                }
                "empty" => {
                    expect.empty = value == "true";
                    *idx += 1;
                }
                "error" => {
                    expect.error = Some(unquote(value));
                    *idx += 1;
                }
                "hash" => {
                    expect.hash = Some(unquote(value));
                    *idx += 1;
                }
                "precision" => {
                    expect.precision = value.parse().ok();
                    *idx += 1;
                }
                "columns" => {
                    expect.columns = parse_yaml_list(value);
                    *idx += 1;
                }
                "rows" => {
                    *idx += 1;
                    expect.rows = parse_rows(lines, idx);
                }
                _ => {
                    *idx += 1;
                }
            }
        } else {
            // Could be a continuation or unknown
            break;
        }
    }

    Ok(expect)
}

fn parse_rows(lines: &[&str], idx: &mut usize) -> Vec<Vec<String>> {
    let mut rows = Vec::new();

    while *idx < lines.len() {
        let trimmed = lines[*idx].trim();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            *idx += 1;
            continue;
        }

        // A row line starts with "- ["
        if trimmed.starts_with("- [") {
            let inner = &trimmed[2..]; // strip "- "
            let values = parse_yaml_inline_list(inner);
            rows.push(values);
            *idx += 1;
        } else {
            break;
        }
    }

    rows
}

fn parse_string_list(lines: &[&str], idx: &mut usize) -> Vec<String> {
    let mut items = Vec::new();

    while *idx < lines.len() {
        let trimmed = lines[*idx].trim();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            *idx += 1;
            continue;
        }

        if let Some(value) = trimmed.strip_prefix("- ") {
            if value == "|" {
                items.push(parse_block_scalar(lines, idx));
            } else {
                items.push(unquote(value));
                *idx += 1;
            }
        } else {
            break;
        }
    }

    items
}

fn parse_params(lines: &[&str], idx: &mut usize) -> HashMap<String, String> {
    let mut params = HashMap::new();

    while *idx < lines.len() {
        let trimmed = lines[*idx].trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            *idx += 1;
            continue;
        }

        if let Some((key, value)) = parse_kv(trimmed) {
            // Check indent level: params entries are deeply nested (indent >= 6)
            let indent = lines[*idx].len() - lines[*idx].trim_start().len();
            if indent >= 6 {
                // Still in params
                params.insert(key.to_string(), unquote(value));
                *idx += 1;
            } else {
                break;
            }
        } else {
            break;
        }
    }

    params
}

fn parse_variants(lines: &[&str], idx: &mut usize) -> HashMap<String, String> {
    let mut variants = HashMap::new();

    while *idx < lines.len() {
        let trimmed = lines[*idx].trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            *idx += 1;
            continue;
        }

        if let Some((key, value)) = parse_kv(trimmed) {
            let indent = lines[*idx].len() - lines[*idx].trim_start().len();
            if indent >= 6 {
                if value == "|" {
                    variants.insert(key.to_string(), parse_block_scalar(lines, idx));
                } else {
                    variants.insert(key.to_string(), unquote(value));
                    *idx += 1;
                }
            } else {
                break;
            }
        } else {
            break;
        }
    }

    variants
}

// ---------------------------------------------------------------------------
// YAML primitives
// ---------------------------------------------------------------------------

fn parse_kv(s: &str) -> Option<(&str, &str)> {
    // Find first colon not inside quotes
    let mut in_single = false;
    let mut in_double = false;
    for (i, c) in s.char_indices() {
        match c {
            '\'' if !in_double => in_single = !in_single,
            '"' if !in_single => in_double = !in_double,
            ':' if !in_single && !in_double => {
                let key = s[..i].trim();
                let value = s[i + 1..].trim();
                if !key.is_empty() {
                    return Some((key, value));
                }
            }
            _ => {}
        }
    }
    None
}

fn unquote(s: &str) -> String {
    let s = s.trim();
    if (s.starts_with('"') && s.ends_with('"')) || (s.starts_with('\'') && s.ends_with('\'')) {
        let inner = &s[1..s.len() - 1];
        // Only unescape YAML-level escapes (quotes and backslashes).
        // Do NOT process \n or \t here: those are GQL string escapes
        // that the GQL parser handles via unescape_string().
        inner
            .replace("\\\\", "\x00")
            .replace("\\\"", "\"")
            .replace("\\'", "'")
            .replace('\x00', "\\")
    } else {
        s.to_string()
    }
}

fn parse_yaml_list(s: &str) -> Vec<String> {
    let s = s.trim();
    if s == "[]" || s.is_empty() {
        return Vec::new();
    }
    if s.starts_with('[') && s.ends_with(']') {
        let inner = &s[1..s.len() - 1];
        inner
            .split(',')
            .map(|v| unquote(v.trim()))
            .filter(|v| !v.is_empty())
            .collect()
    } else {
        vec![unquote(s)]
    }
}

fn parse_yaml_inline_list(s: &str) -> Vec<String> {
    let s = s.trim();
    if !s.starts_with('[') || !s.ends_with(']') {
        return vec![unquote(s)];
    }
    let inner = &s[1..s.len() - 1];

    // Split by commas, but respect nested brackets and quotes
    let mut items = Vec::new();
    let mut current = String::new();
    let mut depth = 0;
    let mut in_single = false;
    let mut in_double = false;

    for c in inner.chars() {
        match c {
            '\'' if !in_double && depth == 0 => {
                in_single = !in_single;
                current.push(c);
            }
            '"' if !in_single && depth == 0 => {
                in_double = !in_double;
                current.push(c);
            }
            '[' | '{' if !in_single && !in_double => {
                depth += 1;
                current.push(c);
            }
            ']' | '}' if !in_single && !in_double => {
                depth -= 1;
                current.push(c);
            }
            ',' if depth == 0 && !in_single && !in_double => {
                items.push(unquote(current.trim()));
                current.clear();
            }
            _ => current.push(c),
        }
    }
    let last = current.trim();
    if !last.is_empty() {
        items.push(unquote(last));
    }

    items
}

fn parse_block_scalar(lines: &[&str], idx: &mut usize) -> String {
    // Current line ends with "|", advance past it
    *idx += 1;

    // Determine indent of block content
    let block_indent = if *idx < lines.len() {
        let line = lines[*idx];
        line.len() - line.trim_start().len()
    } else {
        return String::new();
    };

    let mut result = String::new();
    while *idx < lines.len() {
        let line = lines[*idx];
        let trimmed = line.trim();

        if trimmed.is_empty() {
            result.push('\n');
            *idx += 1;
            continue;
        }

        let current_indent = line.len() - line.trim_start().len();
        if current_indent < block_indent {
            break;
        }

        if !result.is_empty() {
            result.push('\n');
        }
        // Strip the block indent
        if line.len() >= block_indent {
            result.push_str(&line[block_indent..]);
        } else {
            result.push_str(trimmed);
        }
        *idx += 1;
    }

    result.trim_end().to_string()
}

fn skip_blank_and_comments(lines: &[&str], idx: &mut usize) {
    while *idx < lines.len() {
        let trimmed = lines[*idx].trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            *idx += 1;
        } else {
            break;
        }
    }
}

fn walk_dir(dir: &Path) -> Vec<PathBuf> {
    let mut result = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                result.extend(walk_dir(&path));
            } else {
                result.push(path);
            }
        }
    }
    result.sort();
    result
}

// ---------------------------------------------------------------------------
// Test code generation
// ---------------------------------------------------------------------------

fn sanitize_module_name(path: &str) -> String {
    path.replace('/', "_")
        .replace(['.', '-', ' '], "_")
        .to_lowercase()
}

fn sanitize_test_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect::<String>()
        .to_lowercase()
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn generate_tests(
    output: &mut String,
    file: &GtestFile,
    module_name: &str,
    rel_path: &str,
) -> usize {
    let mut count = 0;

    writeln!(output, "mod {module_name} {{").unwrap();
    writeln!(output, "    #[allow(unused_imports)]").unwrap();
    writeln!(output, "    use super::*;").unwrap();
    writeln!(output).unwrap();

    for tc in &file.tests {
        // Skip tests with skip field
        if tc.skip.is_some() {
            writeln!(
                output,
                "    #[test]\n    #[ignore = \"skipped in .gtest\"]\n    fn {}() {{}}\n",
                sanitize_test_name(&tc.name)
            )
            .unwrap();
            count += 1;
            continue;
        }

        // Handle rosetta variants
        if !tc.variants.is_empty() {
            for (lang, query) in &tc.variants {
                let fn_name = format!(
                    "{}_{}",
                    sanitize_test_name(&tc.name),
                    sanitize_test_name(lang)
                );
                generate_single_test(
                    output,
                    &fn_name,
                    file,
                    tc,
                    Some(query),
                    Some(lang),
                    rel_path,
                );
                count += 1;
            }
        } else {
            generate_single_test(
                output,
                &sanitize_test_name(&tc.name),
                file,
                tc,
                None,
                None,
                rel_path,
            );
            count += 1;
        }
    }

    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();

    count
}

fn generate_single_test(
    output: &mut String,
    fn_name: &str,
    file: &GtestFile,
    tc: &TestCase,
    query_override: Option<&str>,
    lang_override: Option<&str>,
    rel_path: &str,
) {
    let language = lang_override
        .or(tc.language.as_deref())
        .unwrap_or(&file.meta.language);
    let model = &file.meta.model;

    // Feature gate: languages that require specific feature flags.
    // graphql-rdf needs both "graphql" and "rdf" features.
    let feature_gates: Vec<&str> = match language {
        "cypher" => vec!["cypher"],
        "gremlin" => vec!["gremlin"],
        "graphql" => vec!["graphql"],
        "graphql-rdf" => vec!["graphql", "rdf"],
        "sparql" => vec!["sparql"],
        "sql-pgq" | "sql_pgq" => vec!["sql-pgq"],
        _ => vec![],
    };

    // Requires from file meta + per-test requires
    let mut all_requires: Vec<&str> = file.meta.requires.iter().map(String::as_str).collect();
    for req in &tc.requires {
        if !all_requires.contains(&req.as_str()) {
            all_requires.push(req);
        }
    }
    for fg in feature_gates {
        if !all_requires.contains(&fg) {
            all_requires.push(fg);
        }
    }

    // Only emit #[cfg] for known Cargo features. Binding capabilities
    // (e.g. "int64-safe") are not Cargo features and the Rust runner
    // always has full fidelity, so they pass through without gating.
    const CARGO_FEATURES: &[&str] = &[
        "gql",
        "cypher",
        "sparql",
        "gremlin",
        "graphql",
        "sql-pgq",
        "rdf",
        "algos",
        "vector-index",
        "text-index",
        "hybrid-search",
        "cdc",
        "tiered-storage",
        "succinct-indexes",
        "ring-index",
        "block-stm",
        "wal",
        "spill",
        "mmap",
    ];
    let cargo_requires: Vec<&str> = all_requires
        .iter()
        .filter(|r| CARGO_FEATURES.contains(r))
        .copied()
        .collect();

    if !cargo_requires.is_empty() {
        let cfg_parts: Vec<String> = cargo_requires
            .iter()
            .map(|r| format!("feature = \"{r}\""))
            .collect();
        let cfg = if cfg_parts.len() == 1 {
            cfg_parts[0].clone()
        } else {
            format!("all({})", cfg_parts.join(", "))
        };
        writeln!(output, "    #[cfg({cfg})]").unwrap();
    }

    writeln!(output, "    #[test]").unwrap();
    writeln!(output, "    fn {fn_name}() {{").unwrap();

    // Create DB and load dataset
    writeln!(output, "        let db = GrafeoDB::new_in_memory();").unwrap();

    let effective_dataset = tc.dataset.as_deref().unwrap_or(&file.meta.dataset);
    if effective_dataset != "empty" {
        let dataset_path = format!("tests/spec/datasets/{}.setup", effective_dataset);
        writeln!(
            output,
            "        load_dataset(&db, \"{}\");",
            escape_rust_string(&dataset_path)
        )
        .unwrap();
    }

    // Setup queries run in the file's declared language and model. This allows
    // SPARQL tests to use INSERT DATA in setup, Cypher tests to use CREATE, etc.
    // For rosetta variant tests, setup always uses meta.language (the file default).
    let setup_language = &file.meta.language;
    for setup_q in &tc.setup {
        writeln!(
            output,
            "        execute_query_with_model(&db, \"{}\", \"{}\", \"{}\");",
            escape_rust_string(setup_language),
            escape_rust_string(model),
            escape_rust_string(setup_q)
        )
        .unwrap();
    }

    // Determine the query to execute
    let query = query_override
        .map(String::from)
        .or_else(|| tc.query.clone());
    let queries = if !tc.statements.is_empty() {
        tc.statements.clone()
    } else if let Some(q) = &query {
        vec![q.clone()]
    } else {
        writeln!(
            output,
            "        panic!(\"No query or statements in test '{}' at {}\");",
            tc.name, rel_path
        )
        .unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        return;
    };

    // Execute queries (all but last are fire-and-forget, last captures result)
    if queries.len() == 1 {
        generate_execute_and_assert(output, &queries[0], language, model, tc, false);
    } else {
        let has_params = !tc.params.is_empty();

        // Build params once before the loop so fire-and-forget statements
        // can use them too (e.g. INSERT/SET with $param).
        if has_params {
            generate_params_hashmap(output, &tc.params);
        }

        // Execute all but last (with params so $param in INSERT/SET works)
        for q in &queries[..queries.len() - 1] {
            if has_params {
                writeln!(
                    output,
                    "        execute_query_result_with_params(&db, \"{}\", \"{}\", \"{}\", params.clone()).expect(\"setup statement failed\");",
                    escape_rust_string(language),
                    escape_rust_string(model),
                    escape_rust_string(q),
                )
                .unwrap();
            } else {
                writeln!(
                    output,
                    "        execute_query_with_model(&db, \"{}\", \"{}\", \"{}\");",
                    escape_rust_string(language),
                    escape_rust_string(model),
                    escape_rust_string(q)
                )
                .unwrap();
            }
        }
        // Last query: capture result and assert
        let last = &queries[queries.len() - 1];
        generate_execute_and_assert(output, last, language, model, tc, has_params);
    }

    writeln!(output, "    }}").unwrap();
    writeln!(output).unwrap();
}

fn generate_params_hashmap(output: &mut String, params: &HashMap<String, String>) {
    writeln!(output, "        let params = {{").unwrap();
    writeln!(
        output,
        "            let mut m = std::collections::HashMap::new();"
    )
    .unwrap();
    for (key, value) in params {
        if let Ok(n) = value.parse::<i64>() {
            writeln!(
                output,
                "            m.insert(\"{}\".to_string(), grafeo_common::types::Value::Int64({n}));",
                escape_rust_string(key)
            )
            .unwrap();
        } else if let Ok(f) = value.parse::<f64>() {
            writeln!(
                output,
                "            m.insert(\"{}\".to_string(), grafeo_common::types::Value::Float64({f}_f64));",
                escape_rust_string(key)
            )
            .unwrap();
        } else if value == "true" || value == "false" {
            writeln!(
                output,
                "            m.insert(\"{}\".to_string(), grafeo_common::types::Value::Bool({value}));",
                escape_rust_string(key)
            )
            .unwrap();
        } else {
            writeln!(
                output,
                "            m.insert(\"{}\".to_string(), grafeo_common::types::Value::String(\"{}\".into()));",
                escape_rust_string(key),
                escape_rust_string(value)
            )
            .unwrap();
        }
    }
    writeln!(output, "            m").unwrap();
    writeln!(output, "        }};").unwrap();
}

fn generate_execute_and_assert(
    output: &mut String,
    query: &str,
    language: &str,
    model: &str,
    tc: &TestCase,
    params_already_emitted: bool,
) {
    let expect = &tc.expect;
    let has_params = !tc.params.is_empty();

    // Build params HashMap if test has parameters and not already emitted
    // (multi-statement tests emit params before the fire-and-forget loop).
    if has_params && !params_already_emitted {
        generate_params_hashmap(output, &tc.params);
    }

    // Error case
    if let Some(err_substr) = &expect.error {
        if has_params {
            writeln!(
                output,
                "        let result = execute_query_result_with_params(&db, \"{}\", \"{}\", \"{}\", params);",
                escape_rust_string(language),
                escape_rust_string(model),
                escape_rust_string(query)
            )
            .unwrap();
        } else {
            writeln!(
                output,
                "        let result = execute_query_result(&db, \"{}\", \"{}\", \"{}\");",
                escape_rust_string(language),
                escape_rust_string(model),
                escape_rust_string(query)
            )
            .unwrap();
        }
        writeln!(
            output,
            "        assert!(result.is_err(), \"Expected error containing '{}' but query succeeded\");",
            escape_rust_string(err_substr)
        )
        .unwrap();
        writeln!(
            output,
            "        let err_msg = format!(\"{{}}\", result.unwrap_err());",
        )
        .unwrap();
        writeln!(
            output,
            "        assert!(err_msg.contains(\"{}\"), \"Error '{{}}' does not contain '{}'\", err_msg);",
            escape_rust_string(err_substr),
            escape_rust_string(err_substr)
        )
        .unwrap();
        return;
    }

    // Normal execution
    if has_params {
        writeln!(
            output,
            "        let result = execute_query_result_with_params(&db, \"{}\", \"{}\", \"{}\", params).expect(\"query failed\");",
            escape_rust_string(language),
            escape_rust_string(model),
            escape_rust_string(query)
        )
        .unwrap();
    } else {
        writeln!(
            output,
            "        let result = execute_query_result(&db, \"{}\", \"{}\", \"{}\").expect(\"query failed\");",
            escape_rust_string(language),
            escape_rust_string(model),
            escape_rust_string(query)
        )
        .unwrap();
    }

    // Column assertion (checked before value assertions)
    if !expect.columns.is_empty() {
        let cols: Vec<String> = expect
            .columns
            .iter()
            .map(|c| format!("\"{}\"", escape_rust_string(c)))
            .collect();
        writeln!(
            output,
            "        assert_columns(&result, &[{}]);",
            cols.join(", ")
        )
        .unwrap();
    }

    // Empty check
    if expect.empty {
        writeln!(
            output,
            "        assert_eq!(result.row_count(), 0, \"Expected empty result\");"
        )
        .unwrap();
        return;
    }

    // Count check
    if let Some(count) = expect.count {
        writeln!(
            output,
            "        assert_eq!(result.row_count(), {count}, \"Expected {count} row(s)\");"
        )
        .unwrap();
        return;
    }

    // Hash check
    if let Some(hash) = &expect.hash {
        writeln!(
            output,
            "        assert_hash(&result, \"{}\");",
            escape_rust_string(hash)
        )
        .unwrap();
        return;
    }

    // Rows check
    if !expect.rows.is_empty() {
        // Build expected rows literal
        writeln!(output, "        let expected: Vec<Vec<String>> = vec![").unwrap();
        for row in &expect.rows {
            let cols: Vec<String> = row
                .iter()
                .map(|c| format!("\"{}\".to_string()", escape_rust_string(c)))
                .collect();
            writeln!(output, "            vec![{}],", cols.join(", ")).unwrap();
        }
        writeln!(output, "        ];").unwrap();

        if let Some(precision) = expect.precision {
            writeln!(
                output,
                "        assert_rows_with_precision(&result, &expected, {precision});"
            )
            .unwrap();
        } else if expect.ordered {
            writeln!(output, "        assert_rows_ordered(&result, &expected);").unwrap();
        } else {
            writeln!(output, "        assert_rows_sorted(&result, &expected);").unwrap();
        }
    }
}
